// What are Hooks

// => Hooks are special functions that let you "hook into" react features like state and lifecycle
//    in functional components



// useState:
// Example:

import React, { useState } from 'react';

function Counter() {
  // Declare a new state variable, which we'll call "count"
  const [count, setCount] = useState(0);

  return (
    <div>
      <p>You clicked {count} times</p>
      <button onClick={() => setCount(count + 1)}>
        Click me
      </button>
    </div>
  );
}

export default Counter;


// Explanation
// Importing useState: First, you need to import useState from React.

// Declaring State: You call useState inside a functional component to declare a state variable.
//  In this example, count is the state variable, and setCount is the function used to update count.

// Initial State: The argument passed to useState (in this case, 0) is the initial state value.

// Updating State: You can update the state by calling the state updater function 
// (setCount in this example) with the new state value.


// Key Points

// Multiple State Variables: You can use multiple useState hooks to manage different pieces of state 
// within the same component.

// State Updates are Asynchronous: State updates using setCount are asynchronous, and React may batch 
// multiple updates for performance reasons.

// Functional Updates: If you need to update state based on the previous state, you can pass a 
// function to the updater function:



////////////////////////////////////////////////////////////////////////////////



// Code Generated by Sidekick is for learning and experimentation purposes only.

import React, { useState, useEffect, useContext, useReducer, useRef } from 'react';

// useEffect
// Purpose: Allows you to perform side effects in functional components, such as data fetching, subscriptions, or manual DOM manipulation.
// Usage: Takes a function and an optional dependency array.

function Timer() {
  const [seconds, setSeconds] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setSeconds(prevSeconds => prevSeconds + 1);
    }, 1000);

    return () => clearInterval(interval); // Cleanup on unmount
  }, []); // Empty array means this effect runs once

  return <div>Seconds: {seconds}</div>;
}

// useContext
// Purpose: Allows you to access React context values in functional components.
// Usage: Takes a context object and returns the current context value.

const ThemeContext = React.createContext('light');

function ThemedButton() {
  const theme = useContext(ThemeContext);
  return <button className={theme}>I am styled by theme!</button>;
}

// useReducer
// Purpose: An alternative to useState for managing complex state logic.
// Usage: Similar to Redux reducers, it takes a reducer function and an initial state.

function counterReducer(state, action) {
  switch (action.type) {
    case 'increment':
      return { count: state.count + 1 };
    case 'decrement':
      return { count: state.count - 1 };
    default:
      throw new Error();
  }
}

function Counter() {
  const [state, dispatch] = useReducer(counterReducer, { count: 0 });

  return (
    <div>
      <p>Count: {state.count}</p>
      <button onClick={() => dispatch({ type: 'increment' })}>+</button>
      <button onClick={() => dispatch({ type: 'decrement' })}>-</button>
    </div>
  );
}

// useRef
// Purpose: Allows you to persist values across renders without causing re-renders.
// Usage: Useful for accessing DOM elements directly.

function TextInputWithFocusButton() {
  const inputRef = useRef(null);

  const focusInput = () => {
    inputRef.current.focus();
  };

  return (
    <div>
      <input ref={inputRef} type="text" />
      <button onClick={focusInput}>Focus the input</button>
    </div>
  );
}

// Custom Hooks
// Purpose: Allows you to extract component logic into reusable functions.
// Usage: Custom hooks are regular functions that can call other hooks.

function useWindowWidth() {
  const [width, setWidth] = useState(window.innerWidth);

  useEffect(() => {
    const handleResize = () => setWidth(window.innerWidth);
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  return width;
}

function DisplayWidth() {
  const width = useWindowWidth();
  return <div>Window width: {width}</div>;
}

// Benefits of Hooks
// Simplified Code: Hooks allow you to use state and lifecycle methods without classes, making code easier to read and maintain.
// Reusable Logic: Custom hooks enable you to share logic across components.
// Functional Components: Encourages the use of functional components, which are simpler and more predictable than class components.
